Fix stack push/pop count when encountering a method with a modreq return type
Washi1337/AsmResolver pull request #191
Opened 2021-07-26 13:30 UTC by zsr2531

This PR fixes an issue with the `GetStackPopCount` and `GetStackPushCount` methods where if the return type is a `CustomModifierTypeSignature`, whose `BaseType` is `void`, it would get treated as if it actually returned a value.

2021-07-26 20:37 UTC, Washi1337 requested changes

2021-07-26 20:37 UTC, Washi1337 commented on src/AsmResolver.DotNet/Code/Cil/CilInstructionExtensions.cs
> +                || HasReturnValue(parent.Owner.Signature));
Possible NRE when the `Signature` property is `null` (as a result of invalid metadata).

2021-07-26 20:37 UTC, Washi1337 commented on src/AsmResolver.DotNet/Code/Cil/CilInstructionExtensions.cs
> +            return ret?.IsTypeOf("System", "Void") ?? false;
Unnecessary null-coalescing.

2021-07-26 20:40 UTC, Washi1337 commented
Actually, I just realized that `MethodSignatureBase` already defines a property `ReturnsValue`. We should probably move the impl of `HasReturnValue` to that property instead.

2021-07-28 12:50 UTC, zsr2531 commented
Closing because I'll open another PR that is based on the correct branch.

2021-07-28 12:50 UTC, closed without merging